name: Git to GCS
description: Sync Google Cloud Storage buckets with git repo folders
inputs:
  secrets:
    description: Space delimited list of buckets and base64 of corresponding access key files
    required: true
runs:
  using: docker
  image: Dockerfile
branding:
  icon: database
  color: blue
